#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done


if [ ! -f /tmp/state/10-tomcat ]; then
sleep 2

	echo 'Initialization Complete' >/tmp/state/10-tomcat
fi

echo ''
echo '** Starting Tomcat'
exec /usr/local/tomcat/bin/catalina.sh run
