#!/usr/bin/with-contenv bash

### Set Defaults
DO_IPV6=${DO_IPV6:-yes}
DO_IPV4=${DO_IPV4:-yes}
DO_UDP=${DO_UDP:-yes}
DO_TCP=${DO_TCP:-yes}
VERBOSITY=${VERBOSITY:-0}
NUM_THREADS=${NUM_THREADS:-1}
SO_RCVBUFF=${SO_RCVBUFF:-0}
SO_SNDBUF=${SO_SNDBUF:-0}
SO_REUSEPORT=${SO_REUSEPORT:-no}
EDNS_BUFFER_SIZE=${EDNS_BUFFER_SIZE:-4096}
MSG_CACHE_SIZE=${MSG_CACHE_SIZE:-4m}
RRSET_CACHE_SIZE=${RRSET_CACHE_SIZE:-4m}
CACHE_MIN_TTL=${CACHE_MIN_TTL:-0}
CACHE_MAX_TTL=${CACHE_MAX_TTL:-86400}
CACHE_MAX_NEGATIVE_TTL=${CACHE_MAX_NEGATIVE_TTL:-3600}
HIDE_IDENTITY=${HIDE_IDENTITY:-no}
HIDE_VERSION=${HIDE_VERSION:-no}
STATISTICS_INTERVAL=${STATISTICS_INTERVAL:-0}
STATISTICS_CUMULATIVE=${STATISTICS_CUMULATIVE:-no}
EXTENDED_STATISTICS=${EXTENDED_STATISTICS:-no}

### Adjust Runtime Variables
sed -i 's/{{DO_IPV6}}/'"${DO_IPV6}"'/' /etc/unbound/unbound.conf
sed -i 's/{{DO_IPV4}}/'"${DO_IPV4}"'/' /etc/unbound/unbound.conf
sed -i 's/{{DO_UDP}}/'"${DO_UDP}"'/' /etc/unbound/unbound.conf
sed -i 's/{{DO_TCP}}/'"${DO_TCP}"'/' /etc/unbound/unbound.conf
sed -i 's/{{VERBOSITY}}/'"${VERBOSITY}"'/' /etc/unbound/unbound.conf
sed -i 's/{{NUM_THREADS}}/'"${NUM_THREADS}"'/' /etc/unbound/unbound.conf
sed -i 's/{{SO_RCVBUFF}}/'"${SO_RCVBUFF}"'/' /etc/unbound/unbound.conf
sed -i 's/{{SO_SNDBUF}}/'"${SO_SNDBUF}"'/' /etc/unbound/unbound.conf
sed -i 's/{{SO_REUSEPORT}}/'"${SO_REUSEPORT}"'/' /etc/unbound/unbound.conf
sed -i 's/{{EDNS_BUFFER_SIZE}}/'"${EDNS_BUFFER_SIZE}"'/' /etc/unbound/unbound.conf
sed -i 's/{{MSG_CACHE_SIZE}}/'"${MSG_CACHE_SIZE}"'/' /etc/unbound/unbound.conf
sed -i 's/{{RRSET_CACHE_SIZE}}/'"${RRSET_CACHE_SIZE}"'/' /etc/unbound/unbound.conf
sed -i 's/{{CACHE_MIN_TTL}}/'"${CACHE_MIN_TTL}"'/' /etc/unbound/unbound.conf
sed -i 's/{{CACHE_MAX_TTL}}/'"${CACHE_MAX_TTL}"'/' /etc/unbound/unbound.conf
sed -i 's/{{CACHE_MAX_NEGATIVE_TTL}}/'"${CACHE_MAX_NEGATIVE_TTL}"'/' /etc/unbound/unbound.conf
sed -i 's/{{HIDE_IDENTITY}}/'"${HIDE_IDENTITY}"'/' /etc/unbound/unbound.conf
sed -i 's/{{HIDE_VERSION}}/'"${HIDE_VERSION}"'/' /etc/unbound/unbound.conf
sed -i 's/{{STATISTICS_INTERVAL}}/'"${STATISTICS_INTERVAL}"'/' /etc/unbound/unbound.conf
sed -i 's/{{STATISTICS_CUMULATIVE}}/'"${STATISTICS_CUMULATIVE}"'/' /etc/unbound/unbound.conf
sed -i 's/{{EXTENDED_STATISTICS}}/'"${EXTENDED_STATISTICS}"'/' /etc/unbound/unbound.conf

mkdir -p /tmp/state
touch /tmp/state/10-unbound-init  

