#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/31-dnsmasq ]; then
	mkdir -p /tmp/state
	echo 'Initialization Complete' >/tmp/state/31-dnsmasq
fi

exec webproc --config /etc/dnsmasq.conf -- dnsmasq --no-daemon
