#!/usr/bin/with-contenv bash

  ### Adjust NGINX Runtime Variables
  UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:="2G"}
  LLNG_HANDLER_HOST=${LLNG_HANDLER_HOST="llng-handler"}
  LLNG_HANDLER_PORT=${LLNG_HANDLER_PORT="2884"}
  WEB_USER=${WEB_USER:-admin}
  WEB_PASS=${WEB_PASS:-password}
  
### Map Authentication
  case "$AUTHENTICATION_TYPE" in
      "BASIC")
      htpasswd -b -c /etc/nginx/htpasswd $WEB_USER $WEB_PASS
      sed -i "/ location \//a\ \ \  auth_basic "Protected"; auth_basic_user_file /etc/nginx/htpasswd;" /etc/nginx/conf.d/default.conf
      echo '** [nginx-php-fpm] Setting Basic Authentication'
      ;;
      "LLNG")
      if [ -f "/etc/nginx/conf.d/default.llng" ]; then
        sed -i "s/<LLNG_HANDLER_HOST>/$LLNG_HANDLER_HOST/g" /etc/nginx/conf.d/default.llng
        sed -i "s/<LLNG_HANDLER_PORT>/$LLNG_HANDLER_PORT/g" /etc/nginx/conf.d/default.llng
        echo '** [nginx-php-fpm] Setting LLNG Authentication'
        mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.orig
        mv /etc/nginx/conf.d/default.llng /etc/nginx/conf.d/default.conf
      else
        echo '** [nginx-php-fpm] ERROR: Cannot find specific Configuration for LLNG Authentication exiting.'
        exit 1
      fi
      ;;
      "NONE")
      echo '** [nginx-php-fpm] Relying on Application Authentication'
      ;;
     *)
      echo '** [nginx-php-fpm] Unknown AUTHENTICATION_TYPE option. Relying on Application Authentication'
     ;;
  esac

  sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/nginx/nginx.conf

  if [ "$MAINTENANCE" = "TRUE" ] || [ "$MAINTENANCE" = "true" ];  then
    echo '** MAINTENANCE MODE ACTIVATED - THIS IMAGE WILL NOT SERVE PAGES'
    mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.orig
    mv /etc/nginx/conf.d/maintenance.conf.maint /etc/nginx.conf.d/maintenance.conf
  fi

  
  mkdir -p /data/logs/nginx
  chown -R nginx /data/logs/nginx
  mkdir -p /tmp/nginx
  chown -R nginx /tmp/nginx

  mkdir -p /tmp/state
  touch /tmp/state/09-nginx
