#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/30-sshd ]; then
# generate host keys if not present
ssh-keygen -A

# check wether a random root-password is provided
if [ ! -z "${ROOT_PASSWORD}" ] && [ "${ROOT_PASSWORD}" != "root" ]; then
    echo "root:${ROOT_PASSWORD}" | chpasswd
fi
	mkdir -p /tmp/state
	echo 'Initialization Complete' >/tmp/state/30-sshd
fi

exec /usr/sbin/sshd -D -e "$@"
