#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-redis ]; then

## Redis Setup
	# first arg is `-f` or `--some-option`
	# or first arg is `something.conf`
	if [ "${1#-}" != "$1" ] || [ "${1%.conf}" != "$1" ]; then
		set -- redis-server "$@"
	fi

	# allow the container to be started with `--user`
	if [ "$1" = 'redis-server' -a "$(id -u)" = '0' ]; then
		chown -R redis .
		exec su-exec redis "$0" "$@"
	fi

        mkdir -p /tmp/state
	echo 'Initialization Complete' >/tmp/state/10-redis
fi

echo ''
echo '** Starting Redis..'
exec s6-setuidgid redis redis-server --dir /data

