#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done


if [ ! -f /tmp/state/10-nginx ]; then

	### Check to see if this is a new install, if yes create directories...
	if [ ! -f /data/html/index.html ] ; then
	   echo "** [nginx] No Files found - New Installation Detected......"
	   mkdir -p /data/html
	   touch /data/html/index.html
	   chown nginx /data/html
	fi

	### Force Reset Permissions for Security
    	chown -R nginx /data/html

        mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo ''
echo '** [nginx] Starting nginx..'
exec nginx

