#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

if [[ "$DEBUG_SMTP" = "TRUE" ]] || [[ "$DEBUG_SMTP" = "true" ]] || [[ "$DEBUG_MODE" = "true" ]] || [[ "$DEBUG_MODE" = "TRUE" ]];  then
exec s6-setuidgid mailhog MailHog;
fi
